version: '2'

services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: dockerfile-postgres
    networks:
      default:
        ipv4_address: 10.1.0.4
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo16@2022      
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  odoo17:
    container_name: odoo
    build:
      context: .
      dockerfile: dockerfile-odoo
    user: root
    depends_on:
      - db
    networks:
      default:
        ipv4_address: 10.1.0.3
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo16@2022
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      # - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
      - ./root:/root # for Odoo filestore
    restart: always  # run as a service

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: dockerfile-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./key.pem:/root/ssl/key.pem
      - ./cert.pem:/root/ssl/cert.pem
    ports:
      - "443:443"
    networks:
      default:
        ipv4_address: 10.1.0.2
    depends_on: 
      - odoo17
    restart: always  # run as a service

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/16
          gateway: 10.1.0.1
