version: '2'

services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: dockerfile-postgres
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo16@2022      
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    volumes:
        - /mnt/users/ceecam/postgresql:/var/lib/postgresql/data

  odoo17:
    container_name: odoo
    build:
      context: .
      dockerfile: dockerfile-odoo
    user: root
    depends_on:
      - db
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo16@2022
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      # - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      - /mnt/users/ceecam/addons:/mnt/extra-addons
      - /mnt/users/ceecam/etc:/etc/odoo
      - /mnt/users/ceecam/root:/root # for Odoo filestore
    restart: always  # run as a service

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: dockerfile-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./key.pem:/root/ssl/key.pem
      - ./cert.pem:/root/ssl/cert.pem
    ports:
      - "443:443"
      - "8080:80"
    depends_on: 
      - odoo17
    restart: always  # run as a service

