FROM postgres:16

# Install cron
RUN apt-get update && apt-get -y install cron

# Copy the pg credentials file
COPY .pgpass /root/

# Permission the pg credentials file
RUN chmod 600 /root/.pgpass

# Copy the crontab file to the cron.d directory
COPY crontab /etc/cron.d/crontab

# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/crontab

# Create the log file to be able to run tail
RUN touch /var/log/cron.log

# Run the command on container startup
# CMD cron && tail -f /var/log/cron.log

# Add any customizations you need here

